Finished
webmarkyn/Design-Teardown pull request #3
Opened 2019-09-23 19:51 UTC by webmarkyn

2019-09-23 20:33 UTC, wathigo commented
**Reviewing**

2019-09-23 21:23 UTC, whiz25 requested changes
## Good job guys :thumbsup:
- [ ] Please fix the ```stickler``` checks and submit for another review.
- [ ] Make your README more professional. Improve the formatting.

2019-09-25 23:43 UTC, Redvanisation approved these changes
### Hello @webmarkyn and @rkyankya  🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

- However, please **fix the error mentioned in the comment** I made below before submitting the project completion form.

### Project approved! you may merge to master. 🚀 

### Good luck! 🍀

2019-09-25 23:43 UTC, Redvanisation commented on index.html
> +                <li class="taglist-item" text-decoration="none"><a href="#">Performance</a></li>
There is no HTML attribute such as "text-decoration", please delete it.

2019-09-30 20:25 UTC, merged